services:
  wiremock:
    image: wiremock/wiremock:latest
    ports:
      - "8080:8080"
    volumes:
      - ./WireMock.IntegrationTests/mappings:/home/wiremock/mappings
    environment:
      - WIREMOCK_OPTIONS=--verbose
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/__admin/health"]
      interval: 10s
      timeout: 5s
      retries: 3

  integration-tests:
    build:
      context: .
      dockerfile: WireMock.IntegrationTests/Dockerfile
    depends_on:
      wiremock:
        condition: service_healthy
    environment:
      - WIREMOCK_URL=http://wiremock:8080
      - ASPNETCORE_ENVIRONMENT=Development 